version: '3'
services:

  #PHP Service
  velolog-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: velolog-app
    restart: unless-stopped
    tty: true
    env_file:
      - env/development
    environment:
      SERVICE_NAME: velolog-app
      SERVICE_TAGS: dev
      CT_STRAVA_CLIENT_ID: '26982'
      CT_STRAVA_SECRET_ID: '4b48f353c9727b7fa5c2deb0bd819d8a0d237b03'
      CT_STRAVA_REDIRECT_URI: 'http://localhost:11111/strava/complete-registration'
    working_dir: /var/www
    volumes:
      - ./application/:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - velolog-network

  #Nginx Service
  velolog-webserver:
    image: nginx:alpine
    container_name: velolog-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "11111:80"
    volumes:
      - ./application/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - velolog-network

  #MySQL Service
  velolog-mysql:
    image: mysql:5.7
    container_name: velolog-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "33333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: velolog
      MYSQL_USER: velolog
      MYSQL_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: velolog-mysql
    volumes:
      - velolog-mysql-data:/var/lib/mysql/
    networks:
      - velolog-network

#Docker Networks
networks:
  velolog-network:
    driver: bridge

#Volumes
volumes:
  velolog-mysql-data:
    driver: local
